/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLayer;

import java.awt.Dimension;

/**
 *
 * @author INFO-JOSEASUNCIONLOP
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnArchivo = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();
        mnCatalogos = new javax.swing.JMenu();
        btnCategorias = new javax.swing.JMenuItem();
        btnClientes = new javax.swing.JMenuItem();
        btnContactos = new javax.swing.JMenuItem();
        btnEstados = new javax.swing.JMenuItem();
        btnLocalidades = new javax.swing.JMenuItem();
        btnMunicipios = new javax.swing.JMenuItem();
        btnProductos = new javax.swing.JMenuItem();
        btnProductosProvedores = new javax.swing.JMenuItem();
        btnProveedores = new javax.swing.JMenuItem();
        btnSucursales = new javax.swing.JMenuItem();
        btnUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        mnArchivo.setText("Archivo");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        mnArchivo.add(btnSalir);

        jMenuBar1.add(mnArchivo);

        mnCatalogos.setText("Catalogos");

        btnCategorias.setText("Categorías");
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnCategorias);

        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnClientes);

        btnContactos.setText("Contactos");
        btnContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactosActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnContactos);

        btnEstados.setText("Estados");
        btnEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadosActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnEstados);

        btnLocalidades.setText("Localidades");
        btnLocalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalidadesActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnLocalidades);

        btnMunicipios.setText("Municipios");
        btnMunicipios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMunicipiosActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnMunicipios);

        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnProductos);

        btnProductosProvedores.setText("Productos-Proveedores");
        btnProductosProvedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosProvedoresActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnProductosProvedores);

        btnProveedores.setText("Proveedores");
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnProveedores);

        btnSucursales.setText("Sucursales");
        btnSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSucursalesActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnSucursales);

        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnUsuarios);

        jMenuBar1.add(mnCatalogos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        frmProductos object = new frmProductos();
        Dimension desktopSize = desktopPane.getSize();
        Dimension jInternalFrameSize = object.getSize();
        object.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        desktopPane.add(object);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
        frmCategoria object = new frmCategoria();
        Dimension desktopSize = desktopPane.getSize();
        Dimension jInternalFrameSize = object.getSize();
        object.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        desktopPane.add(object);
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        frmClientes object = new frmClientes();
        Dimension desktopSize = desktopPane.getSize();
        Dimension jInternalFrameSize = object.getSize();
        object.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        desktopPane.add(object);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactosActionPerformed
        frmContactos object = new frmContactos();
        Dimension desktopSize = desktopPane.getSize();
        Dimension jInternalFrameSize = object.getSize();
        object.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        desktopPane.add(object);
    }//GEN-LAST:event_btnContactosActionPerformed

    private void btnEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadosActionPerformed
        frmEstados object = new frmEstados();
        Dimension desktopSize = desktopPane.getSize();
        Dimension jInternalFrameSize = object.getSize();
        object.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        desktopPane.add(object);
    }//GEN-LAST:event_btnEstadosActionPerformed

    private void btnLocalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalidadesActionPerformed
        frmLocalidades object = new frmLocalidades();
        Dimension desktopSize = desktopPane.getSize();
        Dimension jInternalFrameSize = object.getSize();
        object.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        desktopPane.add(object);
    }//GEN-LAST:event_btnLocalidadesActionPerformed

    private void btnMunicipiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMunicipiosActionPerformed
        frmMunicipios object = new frmMunicipios();
        Dimension desktopSize = desktopPane.getSize();
        Dimension jInternalFrameSize = object.getSize();
        object.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        desktopPane.add(object);
    }//GEN-LAST:event_btnMunicipiosActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        frmProveedores object = new frmProveedores();
        Dimension desktopSize = desktopPane.getSize();
        Dimension jInternalFrameSize = object.getSize();
        object.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        desktopPane.add(object);
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSucursalesActionPerformed
        frmSucursales object = new frmSucursales();
        Dimension desktopSize = desktopPane.getSize();
        Dimension jInternalFrameSize = object.getSize();
        object.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        desktopPane.add(object);
    }//GEN-LAST:event_btnSucursalesActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        frmUsuarios object = new frmUsuarios();
        Dimension desktopSize = desktopPane.getSize();
        Dimension jInternalFrameSize = object.getSize();
        object.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        desktopPane.add(object);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnProductosProvedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosProvedoresActionPerformed
        frmProductoProveedores object = new frmProductoProveedores();
        Dimension desktopSize = desktopPane.getSize();
        Dimension jInternalFrameSize = object.getSize();
        object.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        desktopPane.add(object);
    }//GEN-LAST:event_btnProductosProvedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCategorias;
    private javax.swing.JMenuItem btnClientes;
    private javax.swing.JMenuItem btnContactos;
    private javax.swing.JMenuItem btnEstados;
    private javax.swing.JMenuItem btnLocalidades;
    private javax.swing.JMenuItem btnMunicipios;
    private javax.swing.JMenuItem btnProductos;
    private javax.swing.JMenuItem btnProductosProvedores;
    private javax.swing.JMenuItem btnProveedores;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenuItem btnSucursales;
    private javax.swing.JMenuItem btnUsuarios;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnArchivo;
    private javax.swing.JMenu mnCatalogos;
    // End of variables declaration//GEN-END:variables
}
